// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoUHQ8nhWPxePA3We9a2QFmdt0Lcfv7Sg',
    appId: '1:471910525337:web:efeafa00cca51e095b8b08',
    messagingSenderId: '471910525337',
    projectId: 'e-commerce-8a73c',
    authDomain: 'e-commerce-8a73c.firebaseapp.com',
    storageBucket: 'e-commerce-8a73c.firebasestorage.app',
    measurementId: 'G-69STXR8XZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMmqQCFc7LINxhH2wAdJ5SUt1fVFJkQkM',
    appId: '1:471910525337:android:bf0aa31adbf425385b8b08',
    messagingSenderId: '471910525337',
    projectId: 'e-commerce-8a73c',
    storageBucket: 'e-commerce-8a73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVBtNadRGu1TequhdKS3V5Z1tH_N4Ar4',
    appId: '1:471910525337:ios:cc09e90bf6d86adf5b8b08',
    messagingSenderId: '471910525337',
    projectId: 'e-commerce-8a73c',
    storageBucket: 'e-commerce-8a73c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGVBtNadRGu1TequhdKS3V5Z1tH_N4Ar4',
    appId: '1:471910525337:ios:cc09e90bf6d86adf5b8b08',
    messagingSenderId: '471910525337',
    projectId: 'e-commerce-8a73c',
    storageBucket: 'e-commerce-8a73c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoUHQ8nhWPxePA3We9a2QFmdt0Lcfv7Sg',
    appId: '1:471910525337:web:93ef9fce3581c9595b8b08',
    messagingSenderId: '471910525337',
    projectId: 'e-commerce-8a73c',
    authDomain: 'e-commerce-8a73c.firebaseapp.com',
    storageBucket: 'e-commerce-8a73c.firebasestorage.app',
    measurementId: 'G-LTN4CRQ3KZ',
  );

}